[package]
name = "marc_match_key"
version = "0.1.0"
edition = "2021"
authors = ["Mark Zelesky <mzelesky@princeton.edu>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
