version: 2.1
jobs:
  test:
    parameters:
      ruby:
        description: "Ruby version"
        default: "3.3.6"
        type: "string"
    docker:
      - image: cimg/ruby:<< parameters.ruby >>
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.6.3
            bundle install
            bundle exec rspec
  rubocop:
    parameters:
    docker:
      - image: cimg/ruby:3.2.6
    steps:
      - checkout
      - run:
          name: Run rubocop
          command: |
            gem install bundler -v 2.6.3
            bundle install
            bundle exec rubocop

workflows:
  all-tests:
    jobs:
      - rubocop
      - test:
          matrix:
            parameters:
              ruby: ["3.2.6", "3.3.6", "3.4.1"]
